I-question-this/red-bot-dad-cog

dad.py

By react I mean put a reaction that
considers mean on the message.
Closes #13

Dad will ground people who react meanly.

---

jokes/ok_boomer.py

If you're offended by "okay boomer" you're part of the
problem.
Closes #6

Adds "ok zoomer" in emojis in response to "okay boomer"

---

dad.py
jokes/__init__.py
jokes/chores.py
jokes/her.py
jokes/i_am_dad.py
jokes/joke.py
jokes/ok_boomer.py
jokes/rank.py
jokes/smashing.py
jokes/util.py

Adds various doc strings and shortens line lengths.

---

dad.py
jokes/chores.py

This was done via changing the Chore data into
class data instead of instance data.
This should also be done with the other jokes,
but it's not super important. (created #27)
Closes #26

Adds command to request a user complete a chore.

---

dad.py

Honestly what it should have been called initially.
Closes #29

Changes request_chore_from to request_chore_for.

---

dad.py

Adds more varied responses to when a user is to be punished, thus closing #35.

Adds more varied responses.

---

dad.py
jokes/chores.py

No body asked for it, but we'll a love to garner his love.
Closes #38

Adds "favoritism" to Dad

---

dad.py

Closes #51 
Also changes "reset" commands to reflect forgetting about hatred and favoritism. @mayersjd I hope you don't mind that I changed that verbage.

Adds "most hated child"

---

dad.py

No functionality change.
Closes #59

Fixed spelling error in "calculate_favoritism_in_guild"

---

README.md

Updates README.md with user and developer info

---

dad.py

Closes #62 
This means that #41 was not properly bug checked when the pull request was made.

Resolves bug in "thank_message_author"

---

dad.py

Users have frequently been confused on how
Dad works, this will help them out.
Closes #71

Adds command to explain Dad's whims.

---

dad.py

Closes #45
Closes #46 
Closes #2

Adds more emojis, words, and dads.

---

dad.py
jokes/ok_boomer.py

Adds reaction to "okay zoomer"

---

dad.py

As the title states, added "Getting milk" status as requested by issue #77.
Disclaimer: New to the contributing arena

add  getting milk status

---

dad.py

It's just not as much fun if not everyone can do this. Closes #80

Removes admin restriction on request_chore_for.

---

dad.py

Adds missing comma.

---

jokes/spongebob_chicken.py

Mocking empty messages is just weird.

No MoRe SpOnGeBoB mOcKiNg FoR eMpTy MeSsAgEs

---

AUTHORS.md
environment.yml

This environment runs python 3.8 and the latest version of RedBot.
[How to add the conda environment from the yml file.](https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#creating-an-environment-from-an-environment-yml-file)

Adding environment.yml for conda

---

dad.py
jokes/becky.py
jokes/bonk.py
jokes/chores.py
jokes/favoritsm.py
jokes/her.py
jokes/i_am_dad.py
jokes/joke.py
jokes/naughty.py
jokes/ok_boomer.py
jokes/rank.py
jokes/senpai.py
jokes/simply.py
jokes/smashing.py
jokes/society.py
jokes/spongebob_chicken.py
jokes/stickbug.py
jokes/thats_fair.py

Refactors Log Statements

---

README.md
jokes/__init__.py
jokes/byeah.py

Adds byeah.

---

jokes/byeah.py

One was a bug fix, the other a kind of bug fix.

Tweaks to byeah

---

jokes/favoritism.py

Adds word boundaries.
closes #120

Makes words for favoritism more explicit.

---

dad.py

Fix was to recreate the message for
each server it was to be sent to.
Closes #101

Correctly sends to multiple servers.

---

dad.py
jokes/canceled.py
version.py

Adds the ability to specify a reason for canceling.
closes #132

Adds Reason to Cancelling

---

jokes/bonk.py
jokes/naughty.py
jokes/rank.py
jokes/senpai.py
jokes/simply.py
jokes/smashing.py
jokes/society.py
jokes/spongebob_chicken.py
jokes/stickbug.py

Converting all image sending to embeds closes #157 
Fixes missing rank from the rank messages closes #156 
Fixes bug in stickbug sending
salute gifs contributes to #155 by fixing the minor mistake of stickbug sending salute gifs, but does not solve it.
Adding "fortnite" and "vbucks" as new phrases for society is purely an enhancement that was thought of during this work.

Converts all image sending to embeds.

---

images.py
version.py

Checks if an URL is bad before allowing it to be used. Closes #158, but I'm unable to replicate the non-loading images. I'll simply have to wait until it occurs again. Since it now logs the status of every URL it checks that part should be easier.

Adds image url status check.

---

images.py
version.py

Checks if an URL is bad before allowing it to be used. Closes #158, but I'm unable to replicate the non-loading images. I'll simply have to wait until it occurs again. Since it now logs the status of every URL it checks that part should be easier.

URL Checking
